### ISSUE TITLE
Issue Doctype

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#3]
Custom fields missing in Issue DocType. The fields were getting displayed in the new.selcoerp.com
Raise Warranty Claim Button should appear when issue is in open state.

**Comment by gaurav-naik** [comment]
Fixed Customer Address related problems.

The sms_number field has not been included in the new version. SMS sending logic processes the mobile no in the same way it appears in the mobile no field. Also there is no reference to this field in the code.

Raise Warranty Claim button appears when the workflow state is one of 'Complaint Open','Complaint Assigned To CSE','Complaint Escalated To SBM'. The button did not appear as both complaints on the test server were in the "Complaint Drafted" state.

**Comment by Basawa-SELCO** [comment]
> Fixed Customer Address related problems.
This seems to be not fixed. Please refer the issue no 10.


> The sms_number field has not been included in the new version. SMS sending logic processes the mobile no in the same way it appears in the mobile no field. Also there is no reference to this field in the code.

This is the code in production server. In custom script -Issue-Client
frappe.ui.form.on("Issue", "validate", function(frm, cdt, cdn) {
cur_frm.doc.sms_number = cur_frm.doc.customer_contact_number + "@sms.textlocal.in";
})


> Raise Warranty Claim button appears when the workflow state is one of 'Complaint Open','Complaint Assigned To CSE','Complaint Escalated To SBM'. The button did not appear as both complaints on the test server were in the "Complaint Drafted" state.

We are not able to submit the complaints from the 'Complaint Drafted' State. Hence rest of the workflows can not be checked.

**Comment by gaurav-naik** [comment]
I was able to take the complaint beyond Complaint Drafted. Can you tell me which user tested this, so I can retry with that user's roles?

**Comment by gaurav-naik** [comment]
- [x] Add the sms_number field on Issue
- [x] Auto-set Customer Address on selecting customer
